### ISSUE TITLE
questions about tf.FIFOQueue capacity

### ISSUE THREAD

**Issue by pengsun** [deepmind/scalable_agent#11]
Hi, the code really utilizes many tf techniques and I learn a lot from reading it! I have two questions in regards of the tf.FIFOQueue :

1. the capacity is set to 1:
https://github.com/deepmind/scalable_agent/blob/c63d4f24676aae9611a0456c3b05edc7e77f5c0a/experiment.py#L503
Any particular reason for that?

2. in some use case the data production speed is lower than the data consuming speed (i.e., the environment step/rendering is slow that the gpu learners have to wait for the data batch). In this case, can a larger FIFOQueue capacity alleviate the problem?

**Comment by jsuit** [comment]
https://github.com/deepmind/scalable_agent/issues/5 should answer the first question.

**Comment by lespeholt** [comment]
2. Yes and no. If the actors/environments are consistently slow, then increasing the queue size won't help. You should add more actors and make the individual actors/environments faster. However, if the environments are periodically slow (with long periods) then increasing the queue size could help.

**Comment by pengsun** [comment]
Thanks @jsuit @lespeholt  :)
