### ISSUE TITLE
Performance Question

### ISSUE THREAD

**Issue by zhongyuchen** [deepmind/scalable_agent#13]
I have tried your code with two physical CPUs (both Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz) and I got 400 frames per second in Single-Machine mode on task1 (seekavoid_arena_01). 
Here is what I commanded：
 python experiment.py --num_actors=48 --batch_size=32 --level_name=seekavoid_arena_01

I saw you have got 17k FPS with 48 CPUs in your paper. 
So that's a large gap. I wonder what's happening.

Env. Ubuntu 16.04lts
tensorflow 1.9.0   python2.7
Memory 64 G
logical cpu: 32 (fully uesd when running your code)

**Comment by lespeholt** [comment]
That does indeed seem to be on the low end.

However, a few things to note,

1. The model we use in put in the code is the bigger model where the 17k FPS were with the small model, so try and change that.

2. Disable dynamic batching when using CPU. It doesn't really make sense with CPUs.

3. The environment/TensorFlow layer (PyProcess) is not as optimized as what we have internally (specialized TF ops for each environment). However, it doesn't matter for the big model as for the big model it isn't the bottleneck. I'm considering open sourcing a better open source IPC layer for those who runs the small model.
