### ISSUE TITLE
[Question] Multiple or single host?

### ISSUE THREAD

**Issue by idibidiart** [deepmind/scalable_agent#2]
Hi,

When you say Distributed does that mean multiple hosts (machines) or a single host with multiple GPUs? I don't see how you're specifying how this will scale.

**Comment by lespeholt** [comment]
When we write distributed, we mean the overall setup (actors and learners) are distributed among multiple machines. In this release, we don't include multiple GPUs for the learner. The right implementation for that depends on your setup.

**Comment by lespeholt** [comment]
A bit of knowledge of distributed TensorFlow is needed: https://www.tensorflow.org/deploy/distributed

You should modify the cluster spec in experiment.py to fit your setup and run one actor (and set --task=...) on each machine.

**Comment by idibidiart** [comment]
Ah! I see. It would help a lot to mention in Readme that it’s using Distributed TF and link to the docs for that. I think that would help many new comers. 

Thank you for your help!

**Comment by Maxwell2017** [comment]
> Ah! I see. It would help a lot to mention in Readme that it’s using Distributed TF and link to the docs for that. I think that would help many new comers.
> 
> Thank you for your help!

Excuse me, have you successfully completed distributed training on multiple machines?
@idibidiart
