### ISSUE TITLE
is there any way to have the game window displayed.

### ISSUE THREAD

**Issue by rnunziata** [deepmind/scalable_agent#21]
when running test:

`python experiment.py --mode=test --level_name=dmlab30 --dataset_path=/home/rjn/projects/RL/dataset/ --test_num_episodes=10`

is there any way to have the game window displayed.

**Comment by lespeholt** [comment]
You would need to dump the frames either in PyProcessDmLab or in the agent somewhere.

**Comment by rnunziata** [comment]
I was able to do this by passing in a visibility flag :
```
 enviroments.py
  def step(self, action):
    if self.visable:
       cv2.imshow("xxxxxx",observation[0])
       cv2.waitKey(1)
and to
    experiment.py
       env = create_environment(level_name, seed=i + 1, visable=(i==0))

this can also be passed on the call to test.


```

**Comment by Maxwell2017** [comment]
> cv2.imshow("xxxxxx",observation[0])
>        cv2.waitKey(1)

Have you tried any other visualization methods?
@rnunziata
