### ISSUE TITLE
running learner on GPU 0, actors on GPU 1, having trouble placing actors on GPU 1

### ISSUE THREAD

**Issue by mengdong** [deepmind/scalable_agent#22]
ran learner on GPU 0 by:
CUDA_VISIBLE_DEVICES=0 python experiment.py --job_name=learner --task=0 --num_actors=50 \
    --level_name=explore_goal_locations_small --batch_size=32 --entropy_cost=0.0033391318945337044 \
    --learning_rate=0.00031866995608948655 \
    --total_environment_frames=10000000000 --reward_clipping=soft_asymmetric

ran actor on GPU 1 by:
for i in $(seq 0 49); do CUDA_VISIBLE_DEVICES=1  python experiment.py --job_name=actor --task=$i       --num_actors=50 --level_name=explore_goal_locations_small --dataset_path=/dataset & done;

My environment is created through https://github.com/mengdong/scalable_agent/blob/master/Dockerfile

All scalable agent test passed.

I observe that GPU 0 memory will be drained by learner, hence actor cannot be placed on GPU 0 with out of memory error thrown, only about 10 actors be placed on GPU 1 even though I explicitly specify CUDA_VISIBLE_DEVICES

**Comment by mengdong** [comment]
Also GPU 1 memory usage is about 4GB out of 16GB

**Comment by lespeholt** [comment]
Actor 0 will in this case allocate all memory of GPU 1. See https://www.tensorflow.org/guide/using_gpu#allowing_gpu_memory_growth to avoid it.
In general you probably want to run actors on the CPU, so:
CUDA_VISIBLE_DEVICES='' ...
