### ISSUE TITLE
 unable to find a detail explanation of  INSTR 

### ISSUE THREAD

**Issue by rnunziata** [deepmind/scalable_agent#23]
I am unable to find a detail explanation of  INSTR in the lab documentation , I am also have a very difficult time trying to print the variable out. I get the error shown below: Is there any documentation I can look at?

['RGB_INTERLEAVED', 'INSTR']

`2018-09-27 15:28:42.468383: W tensorflow/core/framework/op_kernel.cc:1263] Unknown: exceptions.AttributeError: 'function' object has no attribute 'send'

I get his error if I use any kind of session , interactive or other. I tried tf.Print and eval both produce same error.
`

**Comment by lespeholt** [comment]
There is some documentation here:
https://github.com/deepmind/lab/blob/master/docs/users/python_api.md

INSTR just means the environment outputs an instruction (a string)

**Comment by rnunziata** [comment]
I tried printing this using  
`instruction = tf.Print(instruction, [instruction]) `
but it prints only [] empty ... when running against dmlab30. What should it print?

**Comment by lespeholt** [comment]
Are you sure you ran against all the dmlab30 levels? You need to run 30 actors to do that. For the language levels the instruction should have content :-)

**Comment by rnunziata** [comment]
I did not run against all 30 levels. Thanks...
