### ISSUE TITLE
Problem running the code snippets in py_process.py 

### ISSUE THREAD

**Issue by mingyr** [deepmind/scalable_agent#30]
There is a small code snippet at the top of the py_process.py source file, however, when I tried to run the code, I have the following problem, can anyone give some suggestion?

```
2019-03-01 17:37:16.260732: W tensorflow/core/framework/op_kernel.cc:1389] Unknown: AttributeError: 'Zeros' object has no attribute 'b'compute''
Traceback (most recent call last):

  File "/home/yuming/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 207, in __call__
    ret = func(*args)

  File "/data/yuming/eeg-dpg/py_process.py", line 89, in py_call
    raise result

AttributeError: 'Zeros' object has no attribute 'b'compute''


```

By the way, I run the code snippet on Red Hat 7.5, with TensorFlow 1.13.1, Python 3.6.3.

I suspect maybe there is a mismatch between encoding? But not for sure.

**Comment by Da-Capo** [comment]
I solved it by adding a `decode()` here
https://github.com/deepmind/scalable_agent/blob/6c0c8a701990fab9053fb338ede9c915c18fa2b1/py_process.py#L142
 ` method_name = str(serialized[0].decode("utf-8"))`

**Comment by mingyr** [comment]
Great, thanks.

I would think there should be some internal fix in TensorFlow, but seems guys there are very funny.

Let's stick to the fix here, thanks again.

I will close the thread.

**Comment by mingyr** [comment]
@Da-Capo Hi, I just had a test, it works both for Python 3.6 and Python 2.7, probably you can make a pull request to address it. Thanks.
