### ISSUE TITLE
question for scan function in vtrace.py

### ISSUE THREAD

**Issue by chagmgang** [deepmind/scalable_agent#37]
I try to understand IMPALA code in this repository.

But I cannot understand the implementation of scan function.
In vtrace.py
```
def scanfunc(acc, sequence_item):
      discount_t, c_t, delta_t = sequence_item
      return delta_t + discount_t * c_t * acc

initial_values = tf.zeros_like(bootstrap_value)
vs_minus_v_xs = tf.scan(
    fn=scanfunc,
    elems=sequences,
    initializer=initial_values,
    parallel_iterations=1,
    back_prop=False,
    reverse=True,  # Computation starts from the back.
    name='scan')
```
I can understand the recursive calculation in order to obtain `vs_minus_v_xs`.
I cannot catch the reason that initial_values are zeros_like of bootstrap_value.

If the initial_values are to become zeros_like, the last term must satisfy the terminal state.
But I cannot find above condition in the code.
If you satisfy this condition in the repository, please refer the line.
Also if you don't satisfy this condition, I want to know the reason.

Thanks for reading.

**Comment by lespeholt** [comment]
Line 244-245 should make it more clear how bootstrap_value is used.
