### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by Maxwell2017** [deepmind/scalable_agent#46]
Hello，How can I visualize agent behavior in test mode?
@lespeholt Looking forward to your reply～

**Comment by lespeholt** [comment]
For DMLab you can pass a record setting, see:
https://github.com/deepmind/lab/blob/master/python/random_agent.py#L193

**Comment by Maxwell2017** [comment]
> For DMLab you can pass a record setting, see:
> https://github.com/deepmind/lab/blob/master/python/random_agent.py#L193

Thank you for your reply. @lespeholt Sorry, I am a new comer in RL field. I still have a question, what is demo File in DMLAB? How do I get this file? Don't you just get the model file after python experiment.py --num_actors=48 --batch_size=32?

**Comment by lespeholt** [comment]
The agent has a test mode:
https://github.com/deepmind/scalable_agent/blob/master/experiment.py#L49

and then you need to visualize or record what you need from the environment you use.

**Comment by Maxwell2017** [comment]
> The agent has a test mode:
> https://github.com/deepmind/scalable_agent/blob/master/experiment.py#L49
> 
> and then you need to visualize or record what you need from the environment you use.

Sorry to bother you again
@lespeholt
when i run the code:python experiment.py --mode=test --test_num_episodes=10,I will get the following information in the terminal
`INFO:tensorflow:Testing level: explore_goal_locations_small
INFO:tensorflow:Mean episode return: 318.000000`
However, I did not find the generated record file. I want to visualize the action track of agent in the map. What other modifications do I need to make in the code?Looking forward to your reply, thanks anyway

**Comment by lespeholt** [comment]
The test mode will just get you the final mean episode return. If you want to record an environment you can wrap the environment with a class that records actions and observations.

**Comment by Maxwell2017** [comment]
Thank you for your reply. I would like to know if you have completed the visualization on DMLAB before? Because I did not find the corresponding interface after referring to the DMLAB project, I do not know how to use the saved actions and observations now :(
@lespeholt
