### ISSUE TITLE
Import dynamic_batching giving error

### ISSUE THREAD

**Issue by Pranav-India** [deepmind/scalable_agent#49]
Hello I am running the scalable_agent on my machine (no gpu) . 

while running the code on single machine is dynamic_batching necessary? I am having following error in the import of the dynamic_batching
`File "/home/pranav/reinforcement/scalable_agent/dynamic_batching.py", line 25, in <module>
    batcher_ops = tf.load_op_library('./batcher.so')
  File "/home/pranav/tf_1/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: ./batcher.so: cannot open shared object file: No such file or directory
`

The error says it is not getting the .so file I don't know how to create it from .cc file I tried 
`g++ -c -o batcher.o batcher.cc`
to create object file and then convert it to .so but I received following error while running this
` #include "tensorflow/core/framework/op.h`
is there a better way? am I missing something.

**Comment by lespeholt** [comment]
Do you run this with the docker file? If not, try that. You can also look at the docker file, it will have the command for compiling the batcher.so

**Comment by Pranav-India** [comment]
Hello @lespeholt thanks for the response , I ran the commands given in the docker file and I got the batcher.so also I am now able to import it.

Thanks
