### ISSUE TITLE
tf.train.Server to TensorFlow 2 Mirrored Strategy

### ISSUE THREAD

**Issue by Pranav-India** [deepmind/scalable_agent#50]
Hello 
I am able to run this repo and also have understood good part of it I am trying to implement this using tf2 and I would like to use mirrored strategy for distributed training. but I am not able to understand how to change **tf.train.Server** as a distributed strategy to mirrored strategy as a distributed learning strategy . I also tried looking for the implementation using tf2 but could not found much on the topic. I know this issue section is only for this repo but I could not find many things regarding IMPALA outside this.

Any help is much appreciated, Thank you.

**Comment by lespeholt** [comment]
Hi, this repo isn't updated at this point. I suggest https://github.com/google-research/seed_rl/ or any of the other IMPALA implementations around.
