### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by AlphaShifter** [deepmind/scalable_agent#9]
Just making sure:
Using the py_process hook, if I close the learner process then all the actor processes will also close?
Thank you!

**Comment by lespeholt** [comment]
In the single machine setup, the environments and their Python processes will close when using the hook. In the distributed setup, there are no PyProcess'es running on the learner, so they won't be closed. In our internal cloud, the actor jobs are set up to shutdown when the learner job is closed.

**Comment by AlphaShifter** [comment]
Are you planning on releasing the multi-learner setup?

**Comment by lespeholt** [comment]
Not for the time being. However, it's fairly easy to implement. You use synchronous TensorFlow optimization, and put a separate tf.FIFOQueue on each learner. Each actor is round robin assigned a learner.
